apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: motion
  namespace: motion
spec:
  ingressClassName: external
  rules:
  - host: webcam.mydomain
    http:
      paths:
      - backend:
          serviceName: motion
          servicePort: 8081
        pathType: ImplementationSpecific
