apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress
namePrefix: webcam-
namespace: raspberrypi-webcam

configMapGenerator:
- files:
  - ./configmaps/motion.conf
  name: motion

#Patch nodeSelector
patches:
  - target:
      kind: Deployment
      name: motion
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value: 
          kubernetes.io/hostname: "piwebcam-0"
      - op: replace
        path: /spec/template/spec/tolerations
        value:
         - effect: NoSchedule
           key: iot
           operator: Equal
           value: "true"
    
# TODO: template selectors to prevent colissions - fixed by using separate namespaces?
